#!/bin/bash

date-diff() {
  declare -a ARGS=()
  until [ -z "$1" ]; do
    case $1 in
       -s|--seconds)  SEC=1;;
       -m|--minutes)  SEC=60;;
       -h|--hours)    SEC=3600;;
       -d|--days)     SEC=86400;;
       *)             ARGS+=("$1");;
    esac
    shift
  done

  if [ "${#ARGS[@]}" -eq 1 ]; then
    DATE2=${ARGS[0]}
    DATE1=now
  elif [ "${#ARGS[@]}" -eq 2 ]; then
    DATE2=${ARGS[1]}
    DATE1=${ARGS[0]}
  else
    echo "Usage: date-diff [-s] [-m] [-h] [-d] <date1> [date2]" >&2
    return 1
  fi

  awk \
    -v EPOCH1=$(date --utc +%s -d "${DATE1}") \
    -v EPOCH2=$(date --utc +%s -d "${DATE2}") \
    -v SEC=${SEC:-1} \
    'BEGIN {print (EPOCH1-EPOCH2)/SEC}'
}
